### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by zygimantus** [wso2-extensions/identity-governance#144]
Hello, I wonder, what is the difference between this project and https://github.com/wso2/carbon-identity-mgt?

**Comment by mefarazath** [comment]
Okay, let me explain.

https://github.com/wso2/carbon-identity-mgt was our old Identity Management Implementation which was based on SOAP admin services.

https://github.com/wso2-extensions/identity-governance our rewrite of the Identity Management features which includes the introduction of a REST API for Identity management functionality such as Password Recovery etc. Old Identity Management Implementation relied on identity-mgt.properties file to read properties related to the features. But with this new implementation, we have introduced Identity Governance connectors which enable use to provide UI-based configuration for Identity Managment features in a multi-tenanted environment.
